# Generated by Django 5.1.1 on 2024-10-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0006_alter_pedido_ventadertalle_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_ventadertalle',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='pedido_ventadertalle',
            name='targeta_credito',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
